apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ct-server
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - contact-tracer.xyz
    secretName: contact-tracer-xyz-tls
  rules:
  - host: contact-tracer.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: ct-server
          servicePort: 5000
